server:
  host: localhost
  port: 8081

spring:
  application:
    name: GoSwiftWeb
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sportclub
    username: root
    password: "password"
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

upload:
  customer:
    path: C://uploads//customer//
  driver:
    path: C://uploads//driver//
  cab_info:
    path: C://uploads//cabinfo//